remote_theme: jekyll/minima@bf9ef989246b63536e9db61082f663f1a6d4d9ce
plugins:
- jekyll-remote-theme 
author: vablings
permalink: /:categories/:title/



navbar-links:
  Home: ""
  Categories: "categories"
  About: "about"
